FROM node:20-alpine AS builder

WORKDIR /app

# Dependencies are copied separately from source code to leverage Docker layer caching
COPY package*.json ./
# All deps (including devDependencies) are needed here for tsc and ts-node
RUN npm ci

COPY tsconfig.json jest.config.ts ./
COPY src ./src

RUN npm run build
# swagger-output.json is generated by npm run build (via npm run swagger)
# and referenced at runtime from the project root

FROM node:20-alpine AS production

WORKDIR /app

# Only production deps — typescript/ts-node are no longer needed since code is already compiled
COPY package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/swagger-output.json ./swagger-output.json

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["node", "dist/index.js"]
